db.url=jdbc:mysql://localhost:3306/smart_bank_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=${DB_USER}
db.password=${DB_PASSWORD}

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}
